"""Agregar campo session_token a Colaborador

Revision ID: 733492306a7a
Revises: 
Create Date: 2024-12-05 23:57:18.097750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '733492306a7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Permisos')
    op.drop_table('Colaboradores_Proyectos_Roles')
    with op.batch_alter_table('Actividades', schema=None) as batch_op:
        batch_op.drop_column('avance')

    with op.batch_alter_table('Colaborador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('fk_roles', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Roles', ['id_rol'], ['id_rol'])

    with op.batch_alter_table('Proyectos', schema=None) as batch_op:
        batch_op.alter_column('id_lider',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('Proyectos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Colaborador', ['id_lider'], ['id_colaborador'])
        batch_op.drop_column('avance')

    with op.batch_alter_table('Roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_rol'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avance', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Proyectos_ibfk_1', 'Colaborador', ['id_lider'], ['id_colaborador'], ondelete='SET NULL')
        batch_op.alter_column('id_lider',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('Colaborador', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_roles', 'Roles', ['id_rol'], ['id_rol'], ondelete='SET NULL')
        batch_op.drop_column('session_token')

    with op.batch_alter_table('Actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avance', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=True))

    op.create_table('Colaboradores_Proyectos_Roles',
    sa.Column('id_colaborador', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_proyecto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_colaborador'], ['Colaborador.id_colaborador'], name='Colaboradores_Proyectos_Roles_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proyecto'], ['Proyectos.id_proyecto'], name='Colaboradores_Proyectos_Roles_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['Roles.id_rol'], name='Colaboradores_Proyectos_Roles_ibfk_3', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_colaborador', 'id_proyecto', 'id_rol'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Permisos',
    sa.Column('id_permiso', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre_permiso', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['Roles.id_rol'], name='Permisos_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_permiso'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
